### ISSUE TITLE
Form validation in tab-inicio

### ISSUE THREAD

**Issue by rafaelgr** [Ariadna-Software/ASW-ArigesMovApp#3]
Take into account form validation in login form. So far we send empty login and password strings, with "Formato incorrecto" (incorrect format) response from API.

**Comment by devragare** [comment]
Received

El 18/01/2016 a las 11:38, rafaelgr escribió:

> Take into account form validation in login form So far we send empty 
> login and password strings, with "Formato incorrecto" (incorrect 
> format) response from API
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Ariadna-Software/ASW-ArigesMovApp/issues/3.

---

El software de antivirus Avast ha analizado este correo electrónico en busca de virus.
https://www.avast.com/antivirus

**Comment by rafaelgr** [comment]
De momento sólo en el tab-inicio, se basa la solución en ngMessages
